#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liber
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="liber")]
	public partial class LiberDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertli_author(li_author instance);
    partial void Updateli_author(li_author instance);
    partial void Deleteli_author(li_author instance);
    partial void Insertli_user(li_user instance);
    partial void Updateli_user(li_user instance);
    partial void Deleteli_user(li_user instance);
    partial void Insertli_basic_preferences(li_basic_preferences instance);
    partial void Updateli_basic_preferences(li_basic_preferences instance);
    partial void Deleteli_basic_preferences(li_basic_preferences instance);
    partial void Insertli_books(li_books instance);
    partial void Updateli_books(li_books instance);
    partial void Deleteli_books(li_books instance);
    partial void Insertli_documents(li_documents instance);
    partial void Updateli_documents(li_documents instance);
    partial void Deleteli_documents(li_documents instance);
    partial void Insertli_editorial(li_editorial instance);
    partial void Updateli_editorial(li_editorial instance);
    partial void Deleteli_editorial(li_editorial instance);
    partial void Insertli_publications(li_publications instance);
    partial void Updateli_publications(li_publications instance);
    partial void Deleteli_publications(li_publications instance);
    partial void Insertli_rss(li_rss instance);
    partial void Updateli_rss(li_rss instance);
    partial void Deleteli_rss(li_rss instance);
    partial void Insertli_saga(li_saga instance);
    partial void Updateli_saga(li_saga instance);
    partial void Deleteli_saga(li_saga instance);
    partial void Insertli_statistics(li_statistics instance);
    partial void Updateli_statistics(li_statistics instance);
    partial void Deleteli_statistics(li_statistics instance);
    #endregion
		
		public LiberDBDataContext() : 
				base(global::Liber.Properties.Settings.Default.liberConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LiberDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LiberDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LiberDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LiberDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<li_author> li_author
		{
			get
			{
				return this.GetTable<li_author>();
			}
		}
		
		public System.Data.Linq.Table<li_user> li_user
		{
			get
			{
				return this.GetTable<li_user>();
			}
		}
		
		public System.Data.Linq.Table<li_basic_preferences> li_basic_preferences
		{
			get
			{
				return this.GetTable<li_basic_preferences>();
			}
		}
		
		public System.Data.Linq.Table<li_books> li_books
		{
			get
			{
				return this.GetTable<li_books>();
			}
		}
		
		public System.Data.Linq.Table<li_documents> li_documents
		{
			get
			{
				return this.GetTable<li_documents>();
			}
		}
		
		public System.Data.Linq.Table<li_editorial> li_editorial
		{
			get
			{
				return this.GetTable<li_editorial>();
			}
		}
		
		public System.Data.Linq.Table<li_publications> li_publications
		{
			get
			{
				return this.GetTable<li_publications>();
			}
		}
		
		public System.Data.Linq.Table<li_rss> li_rss
		{
			get
			{
				return this.GetTable<li_rss>();
			}
		}
		
		public System.Data.Linq.Table<li_saga> li_saga
		{
			get
			{
				return this.GetTable<li_saga>();
			}
		}
		
		public System.Data.Linq.Table<li_statistics> li_statistics
		{
			get
			{
				return this.GetTable<li_statistics>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_author")]
	public partial class li_author : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_author;
		
		private string _firstname;
		
		private string _lastname;
		
		private System.Nullable<System.DateTime> _birthdate;
		
		private System.Nullable<System.DateTime> _deathdate;
		
		private EntitySet<li_books> _li_books;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_authorChanging(string value);
    partial void OnID_authorChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnbirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdateChanged();
    partial void OndeathdateChanging(System.Nullable<System.DateTime> value);
    partial void OndeathdateChanged();
    #endregion
		
		public li_author()
		{
			this._li_books = new EntitySet<li_books>(new Action<li_books>(this.attach_li_books), new Action<li_books>(this.detach_li_books));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_author", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_author
		{
			get
			{
				return this._ID_author;
			}
			set
			{
				if ((this._ID_author != value))
				{
					this.OnID_authorChanging(value);
					this.SendPropertyChanging();
					this._ID_author = value;
					this.SendPropertyChanged("ID_author");
					this.OnID_authorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this.OnbirthdateChanging(value);
					this.SendPropertyChanging();
					this._birthdate = value;
					this.SendPropertyChanged("birthdate");
					this.OnbirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deathdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> deathdate
		{
			get
			{
				return this._deathdate;
			}
			set
			{
				if ((this._deathdate != value))
				{
					this.OndeathdateChanging(value);
					this.SendPropertyChanging();
					this._deathdate = value;
					this.SendPropertyChanged("deathdate");
					this.OndeathdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_author_li_books", Storage="_li_books", ThisKey="ID_author", OtherKey="ID_author")]
		public EntitySet<li_books> li_books
		{
			get
			{
				return this._li_books;
			}
			set
			{
				this._li_books.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_li_books(li_books entity)
		{
			this.SendPropertyChanging();
			entity.li_author = this;
		}
		
		private void detach_li_books(li_books entity)
		{
			this.SendPropertyChanging();
			entity.li_author = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_user")]
	public partial class li_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DNI;
		
		private string _firstname;
		
		private string _lastname;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _email;
		
		private string _direction;
		
		private string _phone;
		
		private string _typeu;
		
		private string _nickname;
		
		private string _passwd;
		
		private EntitySet<li_basic_preferences> _li_basic_preferences;
		
		private EntitySet<li_rss> _li_rss;
		
		private EntitySet<li_statistics> _li_statistics;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndirectionChanging(string value);
    partial void OndirectionChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OntypeuChanging(string value);
    partial void OntypeuChanged();
    partial void OnnicknameChanging(string value);
    partial void OnnicknameChanged();
    partial void OnpasswdChanging(string value);
    partial void OnpasswdChanged();
    #endregion
		
		public li_user()
		{
			this._li_basic_preferences = new EntitySet<li_basic_preferences>(new Action<li_basic_preferences>(this.attach_li_basic_preferences), new Action<li_basic_preferences>(this.detach_li_basic_preferences));
			this._li_rss = new EntitySet<li_rss>(new Action<li_rss>(this.attach_li_rss), new Action<li_rss>(this.detach_li_rss));
			this._li_statistics = new EntitySet<li_statistics>(new Action<li_statistics>(this.attach_li_statistics), new Action<li_statistics>(this.detach_li_statistics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(35)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="VarChar(60)")]
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(9)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeu", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string typeu
		{
			get
			{
				return this._typeu;
			}
			set
			{
				if ((this._typeu != value))
				{
					this.OntypeuChanging(value);
					this.SendPropertyChanging();
					this._typeu = value;
					this.SendPropertyChanged("typeu");
					this.OntypeuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="VarChar(22) NOT NULL", CanBeNull=false)]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this.OnnicknameChanging(value);
					this.SendPropertyChanging();
					this._nickname = value;
					this.SendPropertyChanged("nickname");
					this.OnnicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwd", DbType="VarChar(22) NOT NULL", CanBeNull=false)]
		public string passwd
		{
			get
			{
				return this._passwd;
			}
			set
			{
				if ((this._passwd != value))
				{
					this.OnpasswdChanging(value);
					this.SendPropertyChanging();
					this._passwd = value;
					this.SendPropertyChanged("passwd");
					this.OnpasswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_user_li_basic_preferences", Storage="_li_basic_preferences", ThisKey="DNI", OtherKey="DNI")]
		public EntitySet<li_basic_preferences> li_basic_preferences
		{
			get
			{
				return this._li_basic_preferences;
			}
			set
			{
				this._li_basic_preferences.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_user_li_rss", Storage="_li_rss", ThisKey="DNI", OtherKey="DNI")]
		public EntitySet<li_rss> li_rss
		{
			get
			{
				return this._li_rss;
			}
			set
			{
				this._li_rss.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_user_li_statistics", Storage="_li_statistics", ThisKey="DNI", OtherKey="DNI")]
		public EntitySet<li_statistics> li_statistics
		{
			get
			{
				return this._li_statistics;
			}
			set
			{
				this._li_statistics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_li_basic_preferences(li_basic_preferences entity)
		{
			this.SendPropertyChanging();
			entity.li_user = this;
		}
		
		private void detach_li_basic_preferences(li_basic_preferences entity)
		{
			this.SendPropertyChanging();
			entity.li_user = null;
		}
		
		private void attach_li_rss(li_rss entity)
		{
			this.SendPropertyChanging();
			entity.li_user = this;
		}
		
		private void detach_li_rss(li_rss entity)
		{
			this.SendPropertyChanging();
			entity.li_user = null;
		}
		
		private void attach_li_statistics(li_statistics entity)
		{
			this.SendPropertyChanging();
			entity.li_user = this;
		}
		
		private void detach_li_statistics(li_statistics entity)
		{
			this.SendPropertyChanging();
			entity.li_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_basic_preferences")]
	public partial class li_basic_preferences : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_preferences;
		
		private string _US_lang;
		
		private string _US_formatp;
		
		private bool _US_dinamics;
		
		private string _DNI;
		
		private EntityRef<li_user> _li_user;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_preferencesChanging(string value);
    partial void OnID_preferencesChanged();
    partial void OnUS_langChanging(string value);
    partial void OnUS_langChanged();
    partial void OnUS_formatpChanging(string value);
    partial void OnUS_formatpChanged();
    partial void OnUS_dinamicsChanging(bool value);
    partial void OnUS_dinamicsChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    #endregion
		
		public li_basic_preferences()
		{
			this._li_user = default(EntityRef<li_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_preferences", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_preferences
		{
			get
			{
				return this._ID_preferences;
			}
			set
			{
				if ((this._ID_preferences != value))
				{
					this.OnID_preferencesChanging(value);
					this.SendPropertyChanging();
					this._ID_preferences = value;
					this.SendPropertyChanged("ID_preferences");
					this.OnID_preferencesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_lang", DbType="Char(2)")]
		public string US_lang
		{
			get
			{
				return this._US_lang;
			}
			set
			{
				if ((this._US_lang != value))
				{
					this.OnUS_langChanging(value);
					this.SendPropertyChanging();
					this._US_lang = value;
					this.SendPropertyChanged("US_lang");
					this.OnUS_langChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_formatp", DbType="VarChar(7)")]
		public string US_formatp
		{
			get
			{
				return this._US_formatp;
			}
			set
			{
				if ((this._US_formatp != value))
				{
					this.OnUS_formatpChanging(value);
					this.SendPropertyChanging();
					this._US_formatp = value;
					this.SendPropertyChanged("US_formatp");
					this.OnUS_formatpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_dinamics", DbType="Bit NOT NULL")]
		public bool US_dinamics
		{
			get
			{
				return this._US_dinamics;
			}
			set
			{
				if ((this._US_dinamics != value))
				{
					this.OnUS_dinamicsChanging(value);
					this.SendPropertyChanging();
					this._US_dinamics = value;
					this.SendPropertyChanged("US_dinamics");
					this.OnUS_dinamicsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					if (this._li_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_user_li_basic_preferences", Storage="_li_user", ThisKey="DNI", OtherKey="DNI", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_user li_user
		{
			get
			{
				return this._li_user.Entity;
			}
			set
			{
				li_user previousValue = this._li_user.Entity;
				if (((previousValue != value) 
							|| (this._li_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_user.Entity = null;
						previousValue.li_basic_preferences.Remove(this);
					}
					this._li_user.Entity = value;
					if ((value != null))
					{
						value.li_basic_preferences.Add(this);
						this._DNI = value.DNI;
					}
					else
					{
						this._DNI = default(string);
					}
					this.SendPropertyChanged("li_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_books")]
	public partial class li_books : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_book;
		
		private string _title;
		
		private string _sinopsis;
		
		private string _genre;
		
		private string _portada;
		
		private string _ID_author;
		
		private string _ID_saga;
		
		private EntitySet<li_documents> _li_documents;
		
		private EntitySet<li_publications> _li_publications;
		
		private EntitySet<li_statistics> _li_statistics;
		
		private EntityRef<li_author> _li_author;
		
		private EntityRef<li_saga> _li_saga;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_bookChanging(string value);
    partial void OnID_bookChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnsinopsisChanging(string value);
    partial void OnsinopsisChanged();
    partial void OngenreChanging(string value);
    partial void OngenreChanged();
    partial void OnportadaChanging(string value);
    partial void OnportadaChanged();
    partial void OnID_authorChanging(string value);
    partial void OnID_authorChanged();
    partial void OnID_sagaChanging(string value);
    partial void OnID_sagaChanged();
    #endregion
		
		public li_books()
		{
			this._li_documents = new EntitySet<li_documents>(new Action<li_documents>(this.attach_li_documents), new Action<li_documents>(this.detach_li_documents));
			this._li_publications = new EntitySet<li_publications>(new Action<li_publications>(this.attach_li_publications), new Action<li_publications>(this.detach_li_publications));
			this._li_statistics = new EntitySet<li_statistics>(new Action<li_statistics>(this.attach_li_statistics), new Action<li_statistics>(this.detach_li_statistics));
			this._li_author = default(EntityRef<li_author>);
			this._li_saga = default(EntityRef<li_saga>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_book", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_book
		{
			get
			{
				return this._ID_book;
			}
			set
			{
				if ((this._ID_book != value))
				{
					this.OnID_bookChanging(value);
					this.SendPropertyChanging();
					this._ID_book = value;
					this.SendPropertyChanged("ID_book");
					this.OnID_bookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinopsis", DbType="VarChar(240)")]
		public string sinopsis
		{
			get
			{
				return this._sinopsis;
			}
			set
			{
				if ((this._sinopsis != value))
				{
					this.OnsinopsisChanging(value);
					this.SendPropertyChanging();
					this._sinopsis = value;
					this.SendPropertyChanged("sinopsis");
					this.OnsinopsisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre", DbType="VarChar(15)")]
		public string genre
		{
			get
			{
				return this._genre;
			}
			set
			{
				if ((this._genre != value))
				{
					this.OngenreChanging(value);
					this.SendPropertyChanging();
					this._genre = value;
					this.SendPropertyChanged("genre");
					this.OngenreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portada", DbType="VarChar(256)")]
		public string portada
		{
			get
			{
				return this._portada;
			}
			set
			{
				if ((this._portada != value))
				{
					this.OnportadaChanging(value);
					this.SendPropertyChanging();
					this._portada = value;
					this.SendPropertyChanged("portada");
					this.OnportadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_author", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string ID_author
		{
			get
			{
				return this._ID_author;
			}
			set
			{
				if ((this._ID_author != value))
				{
					if (this._li_author.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_authorChanging(value);
					this.SendPropertyChanging();
					this._ID_author = value;
					this.SendPropertyChanged("ID_author");
					this.OnID_authorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_saga", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string ID_saga
		{
			get
			{
				return this._ID_saga;
			}
			set
			{
				if ((this._ID_saga != value))
				{
					if (this._li_saga.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_sagaChanging(value);
					this.SendPropertyChanging();
					this._ID_saga = value;
					this.SendPropertyChanged("ID_saga");
					this.OnID_sagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_books_li_documents", Storage="_li_documents", ThisKey="ID_book", OtherKey="ID_book")]
		public EntitySet<li_documents> li_documents
		{
			get
			{
				return this._li_documents;
			}
			set
			{
				this._li_documents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_books_li_publications", Storage="_li_publications", ThisKey="ID_book", OtherKey="ID_book")]
		public EntitySet<li_publications> li_publications
		{
			get
			{
				return this._li_publications;
			}
			set
			{
				this._li_publications.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_books_li_statistics", Storage="_li_statistics", ThisKey="ID_book", OtherKey="ID_book")]
		public EntitySet<li_statistics> li_statistics
		{
			get
			{
				return this._li_statistics;
			}
			set
			{
				this._li_statistics.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_author_li_books", Storage="_li_author", ThisKey="ID_author", OtherKey="ID_author", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_author li_author
		{
			get
			{
				return this._li_author.Entity;
			}
			set
			{
				li_author previousValue = this._li_author.Entity;
				if (((previousValue != value) 
							|| (this._li_author.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_author.Entity = null;
						previousValue.li_books.Remove(this);
					}
					this._li_author.Entity = value;
					if ((value != null))
					{
						value.li_books.Add(this);
						this._ID_author = value.ID_author;
					}
					else
					{
						this._ID_author = default(string);
					}
					this.SendPropertyChanged("li_author");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_saga_li_books", Storage="_li_saga", ThisKey="ID_saga", OtherKey="ID_saga", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_saga li_saga
		{
			get
			{
				return this._li_saga.Entity;
			}
			set
			{
				li_saga previousValue = this._li_saga.Entity;
				if (((previousValue != value) 
							|| (this._li_saga.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_saga.Entity = null;
						previousValue.li_books.Remove(this);
					}
					this._li_saga.Entity = value;
					if ((value != null))
					{
						value.li_books.Add(this);
						this._ID_saga = value.ID_saga;
					}
					else
					{
						this._ID_saga = default(string);
					}
					this.SendPropertyChanged("li_saga");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_li_documents(li_documents entity)
		{
			this.SendPropertyChanging();
			entity.li_books = this;
		}
		
		private void detach_li_documents(li_documents entity)
		{
			this.SendPropertyChanging();
			entity.li_books = null;
		}
		
		private void attach_li_publications(li_publications entity)
		{
			this.SendPropertyChanging();
			entity.li_books = this;
		}
		
		private void detach_li_publications(li_publications entity)
		{
			this.SendPropertyChanging();
			entity.li_books = null;
		}
		
		private void attach_li_statistics(li_statistics entity)
		{
			this.SendPropertyChanging();
			entity.li_books = this;
		}
		
		private void detach_li_statistics(li_statistics entity)
		{
			this.SendPropertyChanging();
			entity.li_books = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_documents")]
	public partial class li_documents : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_publication;
		
		private string _path_book;
		
		private string _format_book;
		
		private string _ID_book;
		
		private EntityRef<li_books> _li_books;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_publicationChanging(string value);
    partial void OnID_publicationChanged();
    partial void Onpath_bookChanging(string value);
    partial void Onpath_bookChanged();
    partial void Onformat_bookChanging(string value);
    partial void Onformat_bookChanged();
    partial void OnID_bookChanging(string value);
    partial void OnID_bookChanged();
    #endregion
		
		public li_documents()
		{
			this._li_books = default(EntityRef<li_books>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_publication", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_publication
		{
			get
			{
				return this._ID_publication;
			}
			set
			{
				if ((this._ID_publication != value))
				{
					this.OnID_publicationChanging(value);
					this.SendPropertyChanging();
					this._ID_publication = value;
					this.SendPropertyChanged("ID_publication");
					this.OnID_publicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path_book", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string path_book
		{
			get
			{
				return this._path_book;
			}
			set
			{
				if ((this._path_book != value))
				{
					this.Onpath_bookChanging(value);
					this.SendPropertyChanging();
					this._path_book = value;
					this.SendPropertyChanged("path_book");
					this.Onpath_bookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format_book", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string format_book
		{
			get
			{
				return this._format_book;
			}
			set
			{
				if ((this._format_book != value))
				{
					this.Onformat_bookChanging(value);
					this.SendPropertyChanging();
					this._format_book = value;
					this.SendPropertyChanged("format_book");
					this.Onformat_bookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_book", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_book
		{
			get
			{
				return this._ID_book;
			}
			set
			{
				if ((this._ID_book != value))
				{
					if (this._li_books.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_bookChanging(value);
					this.SendPropertyChanging();
					this._ID_book = value;
					this.SendPropertyChanged("ID_book");
					this.OnID_bookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_books_li_documents", Storage="_li_books", ThisKey="ID_book", OtherKey="ID_book", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_books li_books
		{
			get
			{
				return this._li_books.Entity;
			}
			set
			{
				li_books previousValue = this._li_books.Entity;
				if (((previousValue != value) 
							|| (this._li_books.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_books.Entity = null;
						previousValue.li_documents.Remove(this);
					}
					this._li_books.Entity = value;
					if ((value != null))
					{
						value.li_documents.Add(this);
						this._ID_book = value.ID_book;
					}
					else
					{
						this._ID_book = default(string);
					}
					this.SendPropertyChanged("li_books");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_editorial")]
	public partial class li_editorial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Editorial;
		
		private string _name;
		
		private string _direction;
		
		private string _phone;
		
		private string _webpage;
		
		private EntitySet<li_publications> _li_publications;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EditorialChanging(string value);
    partial void OnID_EditorialChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndirectionChanging(string value);
    partial void OndirectionChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnwebpageChanging(string value);
    partial void OnwebpageChanged();
    #endregion
		
		public li_editorial()
		{
			this._li_publications = new EntitySet<li_publications>(new Action<li_publications>(this.attach_li_publications), new Action<li_publications>(this.detach_li_publications));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Editorial", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Editorial
		{
			get
			{
				return this._ID_Editorial;
			}
			set
			{
				if ((this._ID_Editorial != value))
				{
					this.OnID_EditorialChanging(value);
					this.SendPropertyChanging();
					this._ID_Editorial = value;
					this.SendPropertyChanged("ID_Editorial");
					this.OnID_EditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="VarChar(60)")]
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(9)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_webpage", DbType="VarChar(60)")]
		public string webpage
		{
			get
			{
				return this._webpage;
			}
			set
			{
				if ((this._webpage != value))
				{
					this.OnwebpageChanging(value);
					this.SendPropertyChanging();
					this._webpage = value;
					this.SendPropertyChanged("webpage");
					this.OnwebpageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_editorial_li_publications", Storage="_li_publications", ThisKey="ID_Editorial", OtherKey="ID_Editorial")]
		public EntitySet<li_publications> li_publications
		{
			get
			{
				return this._li_publications;
			}
			set
			{
				this._li_publications.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_li_publications(li_publications entity)
		{
			this.SendPropertyChanging();
			entity.li_editorial = this;
		}
		
		private void detach_li_publications(li_publications entity)
		{
			this.SendPropertyChanging();
			entity.li_editorial = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_publications")]
	public partial class li_publications : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Editorial;
		
		private string _ID_book;
		
		private EntityRef<li_books> _li_books;
		
		private EntityRef<li_editorial> _li_editorial;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EditorialChanging(string value);
    partial void OnID_EditorialChanged();
    partial void OnID_bookChanging(string value);
    partial void OnID_bookChanged();
    #endregion
		
		public li_publications()
		{
			this._li_books = default(EntityRef<li_books>);
			this._li_editorial = default(EntityRef<li_editorial>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Editorial", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Editorial
		{
			get
			{
				return this._ID_Editorial;
			}
			set
			{
				if ((this._ID_Editorial != value))
				{
					if (this._li_editorial.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EditorialChanging(value);
					this.SendPropertyChanging();
					this._ID_Editorial = value;
					this.SendPropertyChanged("ID_Editorial");
					this.OnID_EditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_book", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_book
		{
			get
			{
				return this._ID_book;
			}
			set
			{
				if ((this._ID_book != value))
				{
					if (this._li_books.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_bookChanging(value);
					this.SendPropertyChanging();
					this._ID_book = value;
					this.SendPropertyChanged("ID_book");
					this.OnID_bookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_books_li_publications", Storage="_li_books", ThisKey="ID_book", OtherKey="ID_book", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_books li_books
		{
			get
			{
				return this._li_books.Entity;
			}
			set
			{
				li_books previousValue = this._li_books.Entity;
				if (((previousValue != value) 
							|| (this._li_books.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_books.Entity = null;
						previousValue.li_publications.Remove(this);
					}
					this._li_books.Entity = value;
					if ((value != null))
					{
						value.li_publications.Add(this);
						this._ID_book = value.ID_book;
					}
					else
					{
						this._ID_book = default(string);
					}
					this.SendPropertyChanged("li_books");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_editorial_li_publications", Storage="_li_editorial", ThisKey="ID_Editorial", OtherKey="ID_Editorial", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_editorial li_editorial
		{
			get
			{
				return this._li_editorial.Entity;
			}
			set
			{
				li_editorial previousValue = this._li_editorial.Entity;
				if (((previousValue != value) 
							|| (this._li_editorial.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_editorial.Entity = null;
						previousValue.li_publications.Remove(this);
					}
					this._li_editorial.Entity = value;
					if ((value != null))
					{
						value.li_publications.Add(this);
						this._ID_Editorial = value.ID_Editorial;
					}
					else
					{
						this._ID_Editorial = default(string);
					}
					this.SendPropertyChanged("li_editorial");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_rss")]
	public partial class li_rss : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_rss;
		
		private string _name;
		
		private string _link;
		
		private string _DNI;
		
		private EntityRef<li_user> _li_user;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_rssChanging(string value);
    partial void OnID_rssChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    #endregion
		
		public li_rss()
		{
			this._li_user = default(EntityRef<li_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_rss", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_rss
		{
			get
			{
				return this._ID_rss;
			}
			set
			{
				if ((this._ID_rss != value))
				{
					this.OnID_rssChanging(value);
					this.SendPropertyChanging();
					this._ID_rss = value;
					this.SendPropertyChanged("ID_rss");
					this.OnID_rssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					if (this._li_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_user_li_rss", Storage="_li_user", ThisKey="DNI", OtherKey="DNI", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_user li_user
		{
			get
			{
				return this._li_user.Entity;
			}
			set
			{
				li_user previousValue = this._li_user.Entity;
				if (((previousValue != value) 
							|| (this._li_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_user.Entity = null;
						previousValue.li_rss.Remove(this);
					}
					this._li_user.Entity = value;
					if ((value != null))
					{
						value.li_rss.Add(this);
						this._DNI = value.DNI;
					}
					else
					{
						this._DNI = default(string);
					}
					this.SendPropertyChanged("li_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_saga")]
	public partial class li_saga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_saga;
		
		private string _name;
		
		private string _typep;
		
		private EntitySet<li_books> _li_books;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_sagaChanging(string value);
    partial void OnID_sagaChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypepChanging(string value);
    partial void OntypepChanged();
    #endregion
		
		public li_saga()
		{
			this._li_books = new EntitySet<li_books>(new Action<li_books>(this.attach_li_books), new Action<li_books>(this.detach_li_books));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_saga", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_saga
		{
			get
			{
				return this._ID_saga;
			}
			set
			{
				if ((this._ID_saga != value))
				{
					this.OnID_sagaChanging(value);
					this.SendPropertyChanging();
					this._ID_saga = value;
					this.SendPropertyChanged("ID_saga");
					this.OnID_sagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typep", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string typep
		{
			get
			{
				return this._typep;
			}
			set
			{
				if ((this._typep != value))
				{
					this.OntypepChanging(value);
					this.SendPropertyChanging();
					this._typep = value;
					this.SendPropertyChanged("typep");
					this.OntypepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_saga_li_books", Storage="_li_books", ThisKey="ID_saga", OtherKey="ID_saga")]
		public EntitySet<li_books> li_books
		{
			get
			{
				return this._li_books;
			}
			set
			{
				this._li_books.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_li_books(li_books entity)
		{
			this.SendPropertyChanging();
			entity.li_saga = this;
		}
		
		private void detach_li_books(li_books entity)
		{
			this.SendPropertyChanging();
			entity.li_saga = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.li_statistics")]
	public partial class li_statistics : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_book;
		
		private string _DNI;
		
		private int _numleido;
		
		private int _nota;
		
		private EntityRef<li_user> _li_user;
		
		private EntityRef<li_books> _li_books;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_bookChanging(string value);
    partial void OnID_bookChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnnumleidoChanging(int value);
    partial void OnnumleidoChanged();
    partial void OnnotaChanging(int value);
    partial void OnnotaChanged();
    #endregion
		
		public li_statistics()
		{
			this._li_user = default(EntityRef<li_user>);
			this._li_books = default(EntityRef<li_books>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_book", DbType="Char(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_book
		{
			get
			{
				return this._ID_book;
			}
			set
			{
				if ((this._ID_book != value))
				{
					if (this._li_books.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_bookChanging(value);
					this.SendPropertyChanging();
					this._ID_book = value;
					this.SendPropertyChanged("ID_book");
					this.OnID_bookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					if (this._li_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numleido", DbType="Int NOT NULL")]
		public int numleido
		{
			get
			{
				return this._numleido;
			}
			set
			{
				if ((this._numleido != value))
				{
					this.OnnumleidoChanging(value);
					this.SendPropertyChanging();
					this._numleido = value;
					this.SendPropertyChanged("numleido");
					this.OnnumleidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota", DbType="Int NOT NULL")]
		public int nota
		{
			get
			{
				return this._nota;
			}
			set
			{
				if ((this._nota != value))
				{
					this.OnnotaChanging(value);
					this.SendPropertyChanging();
					this._nota = value;
					this.SendPropertyChanged("nota");
					this.OnnotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_user_li_statistics", Storage="_li_user", ThisKey="DNI", OtherKey="DNI", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_user li_user
		{
			get
			{
				return this._li_user.Entity;
			}
			set
			{
				li_user previousValue = this._li_user.Entity;
				if (((previousValue != value) 
							|| (this._li_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_user.Entity = null;
						previousValue.li_statistics.Remove(this);
					}
					this._li_user.Entity = value;
					if ((value != null))
					{
						value.li_statistics.Add(this);
						this._DNI = value.DNI;
					}
					else
					{
						this._DNI = default(string);
					}
					this.SendPropertyChanged("li_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="li_books_li_statistics", Storage="_li_books", ThisKey="ID_book", OtherKey="ID_book", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public li_books li_books
		{
			get
			{
				return this._li_books.Entity;
			}
			set
			{
				li_books previousValue = this._li_books.Entity;
				if (((previousValue != value) 
							|| (this._li_books.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._li_books.Entity = null;
						previousValue.li_statistics.Remove(this);
					}
					this._li_books.Entity = value;
					if ((value != null))
					{
						value.li_statistics.Add(this);
						this._ID_book = value.ID_book;
					}
					else
					{
						this._ID_book = default(string);
					}
					this.SendPropertyChanged("li_books");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
